name: smart_parser
description: All in one, a generator of recursive descent PEG parsers, tokenizers, and token stream parsers.
version: 2.1.4
homepage: https://github.com/mezoni/smart_parser
topics:
  - parser-generator
  - parsing
  - peg
environment:
  sdk: '>=3.8.0 <4.0.0'
dependencies:
  simple_sparse_list: ^0.1.4
  source_span: ^1.10.1
  strings: ^4.0.1
  unicode: ^1.1.8
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.8
  yaml: ^3.1.3
