name: smart_parser
description: This software is a library that generates source code of recursive descent parsers based on a grammar consisting of the parsing expressions and native Dart language source code
version: 1.0.3
homepage: https://github.com/mezoni/smart_parser
topics:
  - parser-generator
  - parsing
  - peg
environment:
  sdk: '>=3.8.0 <4.0.0'
dependencies:
  simple_sparse_list: ^0.1.4
  source_span: ^1.10.1
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.8
  yaml: ^3.1.3
